### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by malwatte** [mibrito707/cordova-plugin-secure-storage#10]
I saw there are some PRs merged.
@mibrito707  Can you please release a new version with those changes?

Thanks,
Greatly appreciate your work.

**Comment by oddcb** [comment]
@malwatte for the time being you can add it directly via github, for instance: 

```
cordova plugin add https://github.com/mibrito707/cordova-plugin-secure-storage\#1f342bbe0c89bc4bd10d54f9a2d4d34675ae58c8
```

**Comment by mibrito707** [comment]
A new version **4.0.2** was just released with the latest changes 😃
