### ISSUE TITLE
Unable to build on the Mac 

### ISSUE THREAD

**Issue by orest** [mibrito707/cordova-plugin-secure-storage#3]
I'm having this issue when building/running on the Mac. Can you please let me know how to go around it. When i do 
ionic cordova build android i get this error message 

xxx/platforms/android/src/com/crypho/plugins/SecureStorage.java:229: error: local variable title is accessed from within inner class; needs to be declared final
                Intent intent = keyguardManager.createConfirmDeviceCredentialIntent(title, description);
                                                                                    ^
xxx/platforms/android/src/com/crypho/plugins/SecureStorage.java:229: error: local variable description is accessed from within inner class; needs to be declared final
                Intent intent = keyguardManager.createConfirmDeviceCredentialIntent(title, description);
                                                                                           ^
xxx/platforms/android/src/com/crypho/plugins/SecureStorage.java:249: error: local variable userAuthenticationValidityDuration is accessed from within inner class; needs to be declared final
                        RSA.createKeyPair(getContext(), alias, userAuthenticationValidityDuration);

Can you please help.
Thank you

**Comment by Chuckv01** [comment]
@orest @mibrito707 I have this fixed here https://github.com/Chuckv01/cordova-plugin-secure-storage/commit/c962d937a2c855dd8378da88221a63f1a55910c1

I didn't do a pull request as I changed the package name so I could publish the changes to an npm package. Should be pretty easy to merge that commit to this repo though.

**Comment by mibrito707** [comment]
Thanks @Chuckv01, I'll merge that change ASAP

**Comment by giordanocardillo** [comment]
Fixed in PR #6

**Comment by mibrito707** [comment]
Thanks a lot @giordanocardillo 👍
